# Generated by Django 6.0.4 on 2026-04-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_description_homepage_hero_fine_print_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ps_description',
            field=models.TextField(blank=True, help_text='Descriptive paragraph in the Private Setting section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ps_heading',
            field=models.CharField(blank=True, default='A private setting, with the Riviera within easy reach', help_text='Large heading for the Private Setting section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ps_image_left',
            field=models.ForeignKey(blank=True, help_text='Left image in the Private Setting section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ps_image_right',
            field=models.ForeignKey(blank=True, help_text='Right image in the Private Setting section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ps_label',
            field=models.CharField(blank=True, default='Private Setting', help_text="Small label above the heading (e.g. 'Private Setting')", max_length=100, null=True),
        ),
    ]
