# Generated by Django 6.0.4 on 2026-04-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_ps_description_homepage_ps_heading_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ra_button_text',
            field=models.CharField(blank=True, default='Discover', help_text='Text for the Discover button', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ra_description',
            field=models.TextField(blank=True, help_text='Introductory paragraph under the heading', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ra_feature1_desc',
            field=models.TextField(blank=True, help_text='First feature column description', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ra_feature1_title',
            field=models.CharField(blank=True, default='Living spaces', help_text='First feature column title', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ra_feature2_desc',
            field=models.TextField(blank=True, help_text='Second feature column description', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ra_feature2_title',
            field=models.CharField(blank=True, default='Bedrooms', help_text='Second feature column title', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ra_heading',
            field=models.CharField(blank=True, default='Space to breathe, designed for real living', help_text='Large heading for the Rooms & Amenities section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ra_image',
            field=models.ForeignKey(blank=True, help_text='Large image on the left of the Rooms & Amenities section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ra_label',
            field=models.CharField(blank=True, default='Rooms & Amenities', help_text="Small label above the heading (e.g. 'Rooms & Amenities')", max_length=100, null=True),
        ),
    ]
