# Generated by Django 6.0.4 on 2026-04-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_ra_button_text_homepage_ra_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rg_button1_text',
            field=models.CharField(blank=True, default='Inquire', help_text="Primary button label (e.g. 'Inquire')", max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rg_button2_text',
            field=models.CharField(blank=True, default='Next', help_text="Secondary text link label (e.g. 'Next')", max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rg_description',
            field=models.TextField(blank=True, help_text='Descriptive paragraph under the heading', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rg_heading',
            field=models.CharField(blank=True, default='Host your vision in a setting made for it', help_text='Large heading for the Retreats & Gatherings section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rg_image',
            field=models.ForeignKey(blank=True, help_text='Image on the right side of the Retreats & Gatherings section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rg_image_caption_desc',
            field=models.TextField(blank=True, help_text='Short description below the image caption title', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rg_image_caption_title',
            field=models.CharField(blank=True, default='Yoga and wellness retreats', help_text='Bold caption title below the image', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rg_label',
            field=models.CharField(blank=True, default='Retreats & Gatherings', help_text='Small label above the heading', max_length=100, null=True),
        ),
    ]
