# Generated by Django 6.0.4 on 2026-04-17 07:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_rg_button1_text_homepage_rg_button2_text_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hc_bottom_description',
            field=models.TextField(blank=True, help_text='Descriptive paragraph for the bottom block', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hc_bottom_heading',
            field=models.CharField(blank=True, default='Thoughtfully designed so you can switch off', help_text='Large heading for the bottom block', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hc_label',
            field=models.CharField(blank=True, default='Home Comforts', help_text='Small label above the top heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hc_top_button',
            field=models.CharField(blank=True, default='Learn more', help_text="Primary button label (e.g. 'Learn more')", max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hc_top_description',
            field=models.TextField(blank=True, help_text='Descriptive paragraph for the top block', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hc_top_heading',
            field=models.CharField(blank=True, default='Everything you need, without compromise', help_text='Large heading for the top block', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HomeComfortsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_comforts_images', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
