# Generated by Django 6.0.4 on 2026-04-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_hc_bottom_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='olp_button_text',
            field=models.CharField(blank=True, default='Learn more', help_text="Primary button label (e.g. 'Learn more')", max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_description_1',
            field=models.TextField(blank=True, default='Outdoor living here is effortless and inviting with long lunches under the shade drift into evenings that stretch gently into the night, offering space to gather with others or simply sit back and breathe.', help_text='First descriptive paragraph', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_description_2',
            field=models.TextField(blank=True, default='Just steps away, the pool becomes a natural extension of this rhythm, a place to cool off, unwind, or spend entire days lounging by the water, where some of the best memories quietly take shape.', help_text='Second descriptive paragraph', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_heading',
            field=models.CharField(blank=True, default='What the villa offers to make your stay seamless', help_text='Large heading for the section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_label',
            field=models.CharField(blank=True, default='Outdoor Living & Pool', help_text='Small label above the heading', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_outdoor_desc',
            field=models.TextField(blank=True, default='Long lunches under shade, evenings that stretch into night. Space to gather, or simply sit and breathe.', help_text='Description for the Outdoor Living block', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_outdoor_image',
            field=models.ForeignKey(blank=True, help_text='Image for the Outdoor Living block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_outdoor_title',
            field=models.CharField(blank=True, default='Outdoor living', help_text='Title for the Outdoor Living block', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_pool_desc',
            field=models.TextField(blank=True, default='Cool off, unwind, or spend the whole day poolside. This is where most memories are made.', help_text='Description for the Pool block', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_pool_image',
            field=models.ForeignKey(blank=True, help_text='Image for the Pool block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='olp_pool_title',
            field=models.CharField(blank=True, default='Pool', help_text='Title for the Pool block', max_length=150, null=True),
        ),
    ]
