# Generated by Django 6.0.4 on 2026-04-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_olp_button_text_homepage_olp_description_1_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sur_button_text',
            field=models.CharField(blank=True, default='Explore', help_text='Button text', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sur_description',
            field=models.TextField(blank=True, default='Surrounded by vineyards and forest, yet minutes from Saint Tropez. Close enough for beach clubs and restaurants, far enough for complete peace.', help_text='Descriptive paragraph', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sur_heading',
            field=models.CharField(blank=True, default='The best of the South of France, with complete peace and privacy', help_text='Heading for the Surroundings section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sur_image_left',
            field=models.ForeignKey(blank=True, help_text='Image on the top left', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sur_image_right',
            field=models.ForeignKey(blank=True, help_text='Image staggered on the right', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sur_label',
            field=models.CharField(blank=True, default='Surroundings', help_text='Small label above the heading', max_length=100, null=True),
        ),
    ]
