# Generated by Django 6.0.4 on 2026-04-18 06:05

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_sur_button_text_homepage_sur_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rev_description',
            field=models.TextField(blank=True, default='Guests return year after year for the calm, the setting, and the feeling of complete escape', help_text='Descriptive paragraph for the Reviews section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rev_heading',
            field=models.CharField(blank=True, default='A place guests return to', help_text='Heading for the Reviews section', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HomePageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('stars', models.IntegerField(default=5, help_text='Number of stars (1-5)')),
                ('text', models.TextField(help_text='Review text')),
                ('author_name', models.CharField(help_text='Author name', max_length=150)),
                ('author_title', models.CharField(blank=True, help_text='Author title or location', max_length=150, null=True)),
                ('author_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
