# Generated by Django 6.0.4 on 2026-04-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_rev_description_homepage_rev_heading_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='rev_description',
            field=models.TextField(blank=True, default='Guests return year after year for the calm, the setting, and the feeling of complete escape', help_text='Short description beneath the heading', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='rev_heading',
            field=models.CharField(blank=True, default='A place guests return to', help_text='Section heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagereview',
            name='author_image',
            field=models.ForeignKey(blank=True, help_text='Profile picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepagereview',
            name='author_name',
            field=models.CharField(help_text='Guest name', max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagereview',
            name='author_title',
            field=models.CharField(blank=True, help_text='Guest title or location (optional)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homepagereview',
            name='stars',
            field=models.IntegerField(default=5, help_text='Rating out of 5'),
        ),
        migrations.AlterField(
            model_name='homepagereview',
            name='text',
            field=models.TextField(help_text='Review text (shown in italic)'),
        ),
    ]
