# Generated by Django 6.0.4 on 2026-04-18 09:33

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_rev_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='book_description',
            field=models.TextField(blank=True, default='Choose your dates, check availability instantly, and book directly with us for the best experience and rates.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='book_heading',
            field=models.CharField(blank=True, default='Check availability and plan your stay', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='book_label',
            field=models.CharField(blank=True, default='Planning & Booking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bwc_heading',
            field=models.CharField(blank=True, default='Book With Confidence', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whn_heading',
            field=models.CharField(blank=True, default='What Happens Next', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_btn1_text',
            field=models.CharField(blank=True, default='Book Now', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_btn2_text',
            field=models.CharField(blank=True, default='Inquire', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_heading',
            field=models.CharField(blank=True, default='Why Book Directly With Us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='HomePageConfidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='bwc_items', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageWhatHappensNextStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='whn_steps', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageWhyBookBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_benefits', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
