# Generated by Django 6.0.4 on 2026-04-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_book_description_homepage_book_heading_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='nest_button_text',
            field=models.CharField(blank=True, default='Discover more', help_text='CTA button label', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nest_description',
            field=models.TextField(blank=True, help_text='Main descriptive paragraph', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nest_heading',
            field=models.CharField(blank=True, default='Your private retreat, exactly as it should be', help_text='Large heading for the Nest section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nest_image',
            field=models.ForeignKey(blank=True, help_text='Portrait-format image on the left of the Nest section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nest_label',
            field=models.CharField(blank=True, default='The Nest', help_text="Small label above the heading (e.g. 'The Nest')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nest_sub_description',
            field=models.TextField(blank=True, help_text='Second paragraph below a thin divider line', null=True),
        ),
    ]
