# Generated by Django 6.0.4 on 2026-04-20 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_nest_button_text_homepage_nest_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='nest_button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='nest_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='nest_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='nest_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='nest_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='nest_sub_description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='pbp_btn1_text',
            field=models.CharField(blank=True, default='Airbnb', help_text='Label for the first platform button', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pbp_btn1_url',
            field=models.URLField(blank=True, help_text='URL for the Airbnb listing', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pbp_btn2_text',
            field=models.CharField(blank=True, default='Booking.com', help_text='Label for the second platform button', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pbp_btn2_url',
            field=models.URLField(blank=True, help_text='URL for the Booking.com listing', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pbp_description',
            field=models.TextField(blank=True, default='You can also find us on Airbnb or Booking.com if you prefer, while still enjoying the same experience and service.', help_text='Subtitle / description text', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pbp_heading',
            field=models.CharField(blank=True, default='Prefer to book via a platform', help_text="Main heading for the 'Prefer to book via a platform' section", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pbp_image',
            field=models.ForeignKey(blank=True, help_text='Large image displayed below the text in this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
