# Generated by Django 6.0.4 on 2026-04-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_homepage_nest_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='git_email',
            field=models.EmailField(blank=True, default='contact@maisontropez.com', help_text='Contact email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_email_desc',
            field=models.CharField(blank=True, default='For reservations and questions', help_text='Short description under Email label', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_email_label',
            field=models.CharField(blank=True, default='Email', help_text='Label for the email block', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_heading',
            field=models.CharField(blank=True, default='Get in touch', help_text='Main heading for the Get in Touch section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_label',
            field=models.CharField(blank=True, default='Connect', help_text="Small label above the heading (e.g. 'Connect')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_location',
            field=models.CharField(blank=True, default="Cogolin, Provence-Alpes-Côte d'Azur, France", help_text='Location description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_location_label',
            field=models.CharField(blank=True, default='Location', help_text='Label for the location block', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_map_url',
            field=models.URLField(blank=True, help_text="Google Maps URL for 'View on map' link", null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_phone',
            field=models.CharField(blank=True, default='+33 07712 862823', help_text='Contact phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_phone_desc',
            field=models.CharField(blank=True, default='Reach us during business hours', help_text='Short description under Phone label', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_phone_label',
            field=models.CharField(blank=True, default='Phone', help_text='Label for the phone block', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='git_subheading',
            field=models.CharField(blank=True, default='We respond to inquiries within one business day', help_text='Subheading / response time note', max_length=255, null=True),
        ),
    ]
