# Generated by Django 6.0.4 on 2026-04-22 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_git_email_homepage_git_email_desc_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='oor_button_text',
            field=models.CharField(blank=True, default='Explore', help_text='Button label', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='oor_button_url',
            field=models.URLField(blank=True, help_text='URL for the Explore button', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='oor_description',
            field=models.TextField(blank=True, default='We also welcome guests to our villa in the Scottish Highlands.', help_text='Short description paragraph', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='oor_heading',
            field=models.CharField(blank=True, default='Discover our Scottish retreat', help_text='Main heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='oor_image',
            field=models.ForeignKey(blank=True, help_text='Property image displayed on the left', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='oor_label',
            field=models.CharField(blank=True, default='Other Options', help_text='Small label above the heading', max_length=100, null=True),
        ),
    ]
